sudo: false
language: node_js
node_js:
  - "16.0.0"
#cache:
#  directories:
#  - node_modules
branches:
  only:
    - main
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm install
  - npm run build
  - npx prettier --check .
after_success:
  - bash ./deploy.sh
env:
  global:
    - GH_USER: ni-report-viewer
    - GH_REPO: nirv
